### ISSUE TITLE
Internet Explorer requires Event polyfill

### ISSUE THREAD

**Issue by nerdstep** [probablyup/buttermilk#16]
Internet Explorer breaks due to [usage](https://github.com/probablyup/buttermilk/blob/f492f0ea964c5210e580bcc12d5c737db16e63f1/src/utils.js#L147) of the `new Event` constructor. 

It works fine after adding a [polyfill](https://github.com/lifaon74/events-polyfill), but it was somewhat difficult to track this issue down since the error appears as originating in `react-dom`, and at least with a Create React App bootstrapped app, you can't easily test IE in development.

So testing the production build you get this useful error:

```
SCRIPT445: Object doesn't support this action
react-dom.production.min.js (169,13)
```

Initially I was trying to figure out why Babel/core-js wasn't polyfilling this but it seems they're [not focused on DOM related APIs](https://github.com/zloirock/core-js/issues/354).

Anyway, I'm opening this issue because it might help others avoid similar grief trying to debug the problem. Perhaps a quick mention in the README would be warranted?

**Comment by probablyup** [comment]
Ooh interesting. Thanks for surfacing this! Would you be interested in doing a readme PR?

**Comment by nerdstep** [comment]
Sure thing!

As a point of further discussion, it might be more "correct" to use the [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) API instead of [Event](https://developer.mozilla.org/en-US/docs/Web/API/Event).

Either way, both require a polyfill to support IE, though it is [fairly minimal](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill).
