### ISSUE TITLE
Website not loading (minfication error)

### ISSUE THREAD

**Issue by imrvelj** [probablyup/buttermilk#3]
![screenshot_20180416_184608](https://user-images.githubusercontent.com/4303605/38823407-a723f680-41a6-11e8-8e14-07924eddfda2.png)
Opening [https://buttermilk.js.org](https://buttermilk.js.org) yields this error, tested on Chrome and Firefox

[React error 130](https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]=)

**Comment by probablyup** [comment]
Yikes, thanks. Will take a look

**Comment by probablyup** [comment]
I rolled it back in the meantime

**Comment by probablyup** [comment]
Seems to have been a bad dependency upgrade. Fixed here: https://github.com/probablyup/buttermilk/commit/f3de561381219ac4927eaef9f6e6b0b28c23d62f
