### ISSUE TITLE
False redirect to main page with trailing slash /

### ISSUE THREAD

**Issue by Andruschenko** [probablyup/buttermilk#9]
2 issues:

Given the below routes structure:

1. If I go to `https://mypage.com/imprint` everything works find and it shows me the `Imprint` page.
But if I want to go to `https://mypage.com/imprint/` (extra slash at the end) it redirects me to home, i.e. `/` again, but not to `/imprint` where I would expect it to go to.

2. If I got to `https://mypage.com/something` it correctly shows me the 404 page.
But if I go to `https://mypage.com/something/` (extra slash at the end) it redirect me to home, although `something` is not a valid route and it should show the 404 page again!

My routes look as follows:

```js
{
    path: '/',
    render: () => import('./components/Home/index').then(mdl => mdl.default)
},
{
    path: '/imprint',
    render: () => Imprint
},
{
    path: '*',
    render: () => NotFound
}
```

I think it has to do with [URL Normalization](https://en.wikipedia.org/wiki/URL_normalization#Normalizations_that_usually_preserve_semantics) to deal with trailing slashes.

**Comment by probablyup** [comment]
I'll look into this soon! I've been on a work trip for the past week
